version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
  gcp-gcr: circleci/gcp-gcr@0.6.1
jobs:
  build:
    docker:
      - image: circleci/node:12.16.1
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock"}}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock"}}
          paths:
            - ~/.cache/yarn
      - run:
          name: Run Lint
          command: yarn run lint:ci
      - store_test_results:
          path: reports
      - store_artifacts:
          path: reports
  test:
    docker:
      - image: circleci/node:12.16.1
    steps:
      - checkout
      - run:
          name: Install JUnit coverage reporter
          command: yarn add -D jest-junit
      - run:
          name: Run tests with JUnit as reporter
          environment:
            JEST_JUNIT_OUTPUT_DIR: "reports/jest/results.xml"
          command: yarn run test:ci
      - codecov/upload:
          file: ./coverage/lcov.info
      - store_test_results:
          path: reports
      - store_artifacts:
          path: reports
workflows:
  version: 2.1
  build-test-and-push-image:
    jobs:
      - build
      - test:
          requires:
            - build
      - gcp-gcr/build-and-push-image:
          name: deploy
          image: ci-cd
          tag: $CIRCLE_SHA1
          requires:
            - test
          filters:
            branches:
              only:
                - master
