version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.16.1
    steps:
      - checkout
      - run:
          name: Build
          command: yarn run build
  test:
    docker:
      - image: circleci/node:12.16.1
    steps:
      - checkout
      - run:
          name: Install JUnit coverage reporter
          command: yarn add -D jest-junit
      - run:
          name: Run tests with JUnit as reporter
          command: yarn run test:ci
          environment:
            JEST_JUNIT_OUTPUT_DIR: "test-results/jest/results.xml"
      - store_test_results:
          path: test-results
workflows:
  version: 2.1
  build-and-test:
    jobs:
      - build
      - test:
