version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
  gcloud: circleci/gcp-cli@1.8.4
  gcr: circleci/gcp-gcr@0.6.1
  gke: circleci/gcp-gke@1.0.3
  gke-ext:
    orbs:
      gke: circleci/gcp-gke@1.0.3
    commands:
      rollout-image:
        description: Update a deployment's Docker image.
        parameters:
          cluster:
            description: The Kubernetes cluster name.
            type: string
          container:
            description: The Kubernetes container name.
            type: string
          deployment:
            description: The Kubernetes deployment name.
            type: string
          image:
            description: A fully-qualified name for your docker image
            type: string
          namespace:
            default: ''
            description: The Kubernetes namespace name.
            type: string
          tag:
            default: latest
            description: Docker image tag
            type: string
          dry-run:
            default: none
            description: |
              Must be "none", "server", or "client". If client strategy, only print the object that would be sent, without sending it. If server strategy, submit server-side request without persisting the resource.
            type: string
        steps:
          - gke/update-kubeconfig-with-credentials:
              cluster: <<parameters.cluster>>
          - run:
              command: >
                DRY_RUN="<< parameters.dry-run >>"

                if [ -n "<<parameters.namespace>>" ]; then
                  set -- "$@" --namespace="<<parameters.namespace>>"
                fi

                set -- "$@" "--dry-run=${DRY_RUN}"

                kubectl set image deployment <<parameters.deployment>>
                <<parameters.container>>=<<parameters.image>>:<<parameters.tag>> "$@"
              name: Roll out image
  kube: circleci/kubernetes@0.11.0
jobs:
  build:
    docker:
      - image: circleci/node:12.16.2
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock"}}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock"}}
          paths:
            - ~/.cache/yarn
      - run:
          name: Run Lint
          command: yarn run lint:ci
      - store_test_results:
          path: reports
      - store_artifacts:
          path: reports
  test:
    docker:
      - image: circleci/node:12.16.2
    steps:
      - checkout
      - run:
          name: Install JUnit coverage reporter
          command: yarn add -D jest-junit
      - run:
          name: Run tests with JUnit as reporter
          environment:
            JEST_JUNIT_OUTPUT_DIR: "reports/jest/results.xml"
          command: yarn run test:ci
      - codecov/upload:
          file: ./coverage/lcov.info
      - store_test_results:
          path: reports
      - store_artifacts:
          path: reports
  build-and-push-docker-image:
    docker:
      - image: cimg/base:2020.04
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - gcr/gcr-auth
      - gcr/build-image:
          image: ci-cd
          tag: $CIRCLE_SHA1
      - run:
          name: Tag Image
          command: docker tag gcr.io/anoriqq-ci-cd/ci-cd:$CIRCLE_SHA1 gcr.io/anoriqq-ci-cd/ci-cd:latest
      - run: docker image ls
      - gcr/push-image:
          image: ci-cd
      - gcr/push-image:
          image: ci-cd
          tag: $CIRCLE_SHA1
  deploy:
    docker:
      - image: cimg/base:2020.04
    steps:
      - checkout
      - gcloud/install
      - gcloud/initialize
      - gke/install
      - gke/rollout-image:
          cluster: ci-cd-dev
          container: ci-cd
          deployment: ci-cd-deployment
          image: gcr.io/anoriqq-ci-cd/ci-cd
          tag: $CIRCLE_SHA1
  dry-deploy:
    docker:
      - image: cimg/base:2020.04
    steps:
      - checkout
      - gcloud/install
      - gcloud/initialize
      - gke/install
      - gke-ext/rollout-image:
          cluster: ci-cd-dev
          container: ci-cd
          deployment: ci-cd-deployment
          image: gcr.io/anoriqq-ci-cd/ci-cd
          tag: $CIRCLE_SHA1
          dry-run: client
workflows:
  build-test-and-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - build-and-push-docker-image:
          requires:
            - test
      - deploy:
          requires:
            - build-and-push-docker-image
          filters:
            branches:
              only:
                - master
      - dry-deploy:
          requires:
            - build-and-push-docker-image
          filters:
            branches:
              ignore:
                - master
