apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ci-cd-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: anoriqq-ci-cd-static-ip-address
    networking.gke.io/managed-certificates: anoriqq-ci-cd-static-certificate
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: ci-cd
          servicePort: 80

---

apiVersion: networking.gke.io/v1beta1
kind: ManagedCertificate
metadata:
  name: anoriqq-ci-cd-static-certificate
spec:
  domains:
    - p.anoriqq.com
